/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as KangRouteImport } from './routes/kang'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as LargecapRouteImport } from './routes/largecap'
import { Route as MidcapRouteImport } from './routes/midcap'
import { Route as StockCodeRouteImport } from './routes/stock.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const KangRoute = KangRouteImport.update({
  id: '/kang',
  path: '/kang',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const LargecapRoute = LargecapRouteImport.update({
  id: '/largecap',
  path: '/largecap',
  getParentRoute: () => rootRouteImport,
} as any)
const MidcapRoute = MidcapRouteImport.update({
  id: '/midcap',
  path: '/midcap',
  getParentRoute: () => rootRouteImport,
} as any)
const StockCodeRoute = StockCodeRouteImport.update({
  id: '/stock/$code',
  path: '/stock/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/guide': typeof GuideRoute
  '/kang': typeof KangRoute
  '/watchlist': typeof WatchlistRoute
  '/largecap': typeof LargecapRoute
  '/midcap': typeof MidcapRoute
  '/stock/$code': typeof StockCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/guide': typeof GuideRoute
  '/kang': typeof KangRoute
  '/watchlist': typeof WatchlistRoute
  '/largecap': typeof LargecapRoute
  '/midcap': typeof MidcapRoute
  '/stock/$code': typeof StockCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/guide': typeof GuideRoute
  '/kang': typeof KangRoute
  '/watchlist': typeof WatchlistRoute
  '/largecap': typeof LargecapRoute
  '/midcap': typeof MidcapRoute
  '/stock/$code': typeof StockCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/backtest' | '/guide' | '/kang' | '/watchlist' | '/largecap' | '/midcap' | '/stock/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/backtest' | '/guide' | '/kang' | '/watchlist' | '/largecap' | '/midcap' | '/stock/$code'
  id: '__root__' | '/' | '/backtest' | '/guide' | '/kang' | '/watchlist' | '/largecap' | '/midcap' | '/stock/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestRoute: typeof BacktestRoute
  GuideRoute: typeof GuideRoute
  KangRoute: typeof KangRoute
  WatchlistRoute: typeof WatchlistRoute
  LargecapRoute: typeof LargecapRoute
  MidcapRoute: typeof MidcapRoute
  StockCodeRoute: typeof StockCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kang': {
      id: '/kang'
      path: '/kang'
      fullPath: '/kang'
      preLoaderRoute: typeof KangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/largecap': {
      id: '/largecap'
      path: '/largecap'
      fullPath: '/largecap'
      preLoaderRoute: typeof LargecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midcap': {
      id: '/midcap'
      path: '/midcap'
      fullPath: '/midcap'
      preLoaderRoute: typeof MidcapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$code': {
      id: '/stock/$code'
      path: '/stock/$code'
      fullPath: '/stock/$code'
      preLoaderRoute: typeof StockCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktestRoute: BacktestRoute,
  GuideRoute: GuideRoute,
  KangRoute: KangRoute,
  WatchlistRoute: WatchlistRoute,
  LargecapRoute: LargecapRoute,
  MidcapRoute: MidcapRoute,
  StockCodeRoute: StockCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
